# Generated by Django 6.1 on 2026-09-11 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_payment_refund_amount_payment_refunded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='movies_movi_user_id_67e777_idx'), models.Index(fields=['movie', '-viewed_at'], name='movies_movi_movie_i_66cc0c_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie_view')],
            },
        ),
    ]
