# Generated by Django 6.1 on 2026-09-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movieview'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='movies_movi_rating_8fd49a_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['location', 'time'], name='movies_thea_locatio_21dcd8_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['movie', 'time'], name='movies_thea_movie_i_352b0f_idx'),
        ),
    ]
